### ISSUE TITLE
`@resvg/resvg-js` is in production bundle

### ISSUE THREAD

**Issue by pi0** [unjs/docs#25]
```
p why @resvg/resvg-js
Legend: production dependency, optional only, dev only

unjs-docs@0.1.7 /Users/pooya/Code/unjs-docs

dependencies:
nuxt-og-image 2.2.4
└── @resvg/resvg-js 2.6.0

devDependencies:
unjs-docs link:
└─┬ nuxt-og-image 2.2.4
  └── @resvg/resvg-js 2.6.0
```

/cc @harlan-zw seems from `nuxt-og-image`

Cloudflare pages deployment is also broken:

It seems to be also included in Node.js prod bundle. Why we should need this?

```

11:19:18.701 | undefined
-- | --
11:19:18.702 | [error] Cannot resolve "./resvgjs.win32-ia32-msvc.node" from "/opt/buildhome/repo/node_modules/.pnpm/@resvg+resvg-js@2.6.0/node_modules/@resvg/resvg-js/js-binding.js" and externals are not allowed!
11:19:18.702 | at Object.resolveId (/opt/buildhome/repo/node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.4ea992bc.mjs:1973:17)
11:19:18.703 | at async PluginDriver.hookFirstAndGetPlugin (/opt/buildhome/repo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/rollup.js:905:28)
11:19:18.703 | at async resolveId (/opt/buildhome/repo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/rollup.js:18563:26)
11:19:18.703 | at async ModuleLoader.resolveId (/opt/buildhome/repo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/rollup.js:18747:15)
11:19:18.703 | at async /opt/buildhome/repo/node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.9.6/node_modules/@rollup/plugin-commonjs/dist/cjs/index.js:789:12
11:19:18.703 | at async Promise.all (index 9)
11:19:18.704 | at async /opt/buildhome/repo/node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.9.6/node_modules/@rollup/plugin-commonjs/dist/cjs/index.js:781:30
11:19:18.704 | at async rewriteRequireExpressionsAndGetImportBlock (/opt/buildhome/repo/node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.9.6/node_modules/@rollup/plugin-commonjs/dist/cjs/index.js:1358:28)
11:19:18.704 | at async transformCommonjs (/opt/buildhome/repo/node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.9.6/node_modules/@rollup/plugin-commonjs/dist/cjs/index.js:1932:23)
11:19:18.704 | at async transform (/opt/buildhome/repo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/rollup.js:18665:16)
11:19:18.704 | at async ModuleLoader.addModuleSource (/opt/buildhome/repo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/rollup.js:18882:36)
11:19:18.704 |  
11:19:18.704 | [error] Cannot resolve "./resvgjs.win32-ia32-msvc.node" from "/opt/buildhome/repo/node_modules/.pnpm/@resvg+resvg-js@2.6.0/node_modules/@resvg/resvg-js/js-binding.js" and externals are not allowed!
11:19:18.851 | ELIFECYCLE  Command failed with exit code 1.
11:19:18.885 | Failed: Error while executing user command. Exited with error code: 1
11:19:18.894 | Failed: build command exited with code: 1
11:19:20.243 | Failed: error occurred while running build command
```

**Comment by harlan-zw** [comment]
Needed to turn svg to PNG. Maybe related to how it's being deployed? 

I have pages working fine with https://github.com/harlan-zw/nuxt-og-image-playground

**Comment by pi0** [comment]
We use v2 currently would it make a difference? 

From just logs, I can tell main part of the issue is that this dependency have to be externalized for prerendering bundle but it is all bundled.

**Comment by Barbapapazes** [comment]
Merging #5 could help since it will update to v3 (but alos `@resvg/resvg-js` could be included in prod bundle?).

**Comment by harlan-zw** [comment]
I'd highly recommend the v3, it has many improvements in bundling regard but not exactly sure if this specific issue would be solved

**Comment by pi0** [comment]
Okay lets only upgrade it to v3. I hope no big API changes.

**Comment by harlan-zw** [comment]
> Okay lets only upgrade it to v3. I hope no big API changes.

https://nuxtseo.com/og-image/migration-guide/v3

**Comment by pi0** [comment]
Okay, I will try to remember upstream followup if spotted issues with v3 thanks for help. for now used a workround to force static build at least we can move forward.
